### PR TITLE
Some Draconic Armor improvements.

### PR DESCRIPTION
**Pull request by OneEyeMaker**
Now Draconic Armor should protect players from bees' stings.
Also added vis discount for helmet, because it has the same functional, the Goggles of Revealing has.

### CODE REVIEW

**Comment by brandon3055** [comment]
I dont like your fix at all so im fixing it myself.

**Comment by OneEyeMaker** [comment]
@brandon3055 
Ok. So, please, add implementation of these Forestry interfaces. Or, you want, I can rework this fix.

**Comment by OneEyeMaker** [comment]
https://github.com/OneEyeMaker/Draconic-Evolution/commit/9e210c2602fe8be8d38ce0f3daec9a67a836eea3

**Comment by brandon3055** [comment]
I really dont see what that is needed because the armor will already protect against bee stings unless forestry has done something crazy that can bypass the shield.

**Comment by OneEyeMaker** [comment]
@brandon3055 
Draconic armor protects from bee stings, it's correct. But...
1) Now Draconic armor loose protection points when bees attack. And armor consmes energy to restore ones. (Some bees attack so often, that armor consume large amount of energy).
2) Apiarist's armor from Forestry also bees' negative effects (Draconic armor can do it, but... - read #1).
3) Apiarist's armor has a nice feature - Naturalist's goggles, that can help with breeding very much (These goggles is analogue of Goggles of Revealing, but for Forestry).
Draconic armor is the best armor anyone can imagine. And (I think) it should has all nice features, that any other armor has.
That's why I added this code for Forestry support.

**Pull request closed without merging**
