### PR TITLE
Add ja-JP.lang

### PR DESCRIPTION
**Pull request by karakufire**
Translation into Japanese(items, blocks and some descriptions)

### CODE REVIEW

**Comment by brandon3055** [comment]
can you please double check your pull request it looks like more then just the addition of a language file.

**Comment by karakufire** [comment]
Sorry I can't take consideration into your real intention from your comment. Excuse me, but  please in other words?

**Comment by karakufire** [comment]
well, I can't found any problem.

**Comment by karakufire** [comment]
What is wrong...

**Pull request closed without merging**
