### PR TITLE
Edits to the copy in the manual

### PR DESCRIPTION
**Pull request by requnix**
I'm not sure if this is something you want done, but I've just gone through the the text for the manual and tried to clean it up a little. If I've changed anything in a way you're not happy with, let me know and I'll make the necessary changes.

### CODE REVIEW

**Comment by brandon3055** [comment]
I appreciate the spelling and grammar corrections i have been meaning to get someone to proof read that for a while. but there is an issue with the format changes you made. The way the manual is coded a single string e.g.
<code>"Learning how draconic powers interact with the powers of the endermen, you have created the ultimate teleporter. You can now store up to 100 locations and using the endermen’s own pearls as fuel, created something that can teleport you extreme distances even across dimensions at will. Shift right click to open the GUI. Most functionality should be self explanatory. On the left is the destination list. Each destination has a lock button that prevents you from accidentally overwriting or deleting it. On the right starting from the top you have information about the selected destination, An option to rename the selected destination, An option to change the selected destination to your current coordinates and an option to delete the selected destination. Under that is the fuel, An option to teleport to the selected destination, an option to add a new destination (your current location), And an option to add fuel (Ender pearls from your inventory) Shift click to add a stack. You can also shift+Scroll with the item in your hand to cycle through the destinations without opening the gui and right click to teleport. You can also teleport players and mobs by left clicking them however players must be holding shift and mobs can not be teleported across dimensions.",</code>
is one paragraph which may not look good in the JSON as one very long line of text but that is irreverent because it is automatically formatted to make it fit in the manual.

So when you split that up into separate strings like you did it turns it into a bunch of really short paragraphs. Or was that your intention?

**Comment by requnix** [comment]
Yeah, I did that to split it up so it's easier to read. Seeing as each entry renders on its own page I thought it shouldn't cause too much of an issue.

**Comment by brandon3055** [comment]
ok in that case i will merge it and see how it looks.

**Comment by brandon3055** [comment]
yea i like that. makes it a lot easier to read thanks!

**Comment by requnix** [comment]
Great. Thanks for having a look.

**Pull request merged**
