### PR TITLE
Update en_US.lang

### PR DESCRIPTION
**Pull request by cwbit**
fixed some word and grammar snafus.

### CODE REVIEW

**Comment by brandon3055** [comment]
Thanks for that but im not going to merge it because a lot of what you modified is being removed soon.

**Comment by cwbit** [comment]
bah..

**Comment by brandon3055** [comment]
Will leave this open because i will be using some of what you changed.

**Comment by GreatOrator** [comment]
So many changes have been made since this pull it is no longer a viable request.  If you would like to re-pull using the new content and resubmit that would be awesome!

**Pull request closed without merging**
