### PR TITLE
Various Spelling and Grammar Fixes

### PR DESCRIPTION
**Pull request by FoxMcloud5655**

### CODE REVIEW

**Comment by covers1624** [comment]
The `en_us.json` file is machine generated, you will want to edit the DataGenerator and re-run it: <https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/datagen/LangGenerator.java>

**Comment by brandon3055** [comment]
I would prefer you didn't reformat the entire LanguageGenerator class. I'm guessing whatever IDE your using must not respect the `//@formatter:off` / `//@formatter:on` flags.

**Comment by FoxMcloud5655** [comment]
Actually, that was all on me.  A lot of the entries had commas that were arbitrarily on the left or the right of the spaces, and some of the spaces didn't line everything up.  I can revert that change if you want me to.

**Comment by brandon3055** [comment]
I would prefer you revert and just change the lines you need to. Sure its a bit messy the way i have it but it works for me for now. Generally you want to avoid reformatting entire classes in pr's because it makes it impossible to see what lines you have changed. It also makes merge conflicts much more painful to fix. The reason i have not cleaned this class up yet is because its because i am leaving it until de is in a more finished state.

**Comment by brandon3055** [comment]
On second thought. If you can just fix the merge conflict with my recent changes i will accept it as is.

**Comment by FoxMcloud5655** [comment]
I understand and will try to not make the same mistake again.

**Comment by FoxMcloud5655** [comment]
Ready to go whenever you want.

**Pull request merged**
