### PR TITLE
Add more config options.

### PR DESCRIPTION
**Pull request by OneEyeMaker**
Hello.
Purpose of these changes is simple. Draconic Evolution is very cool mod, but it's very hard to configure it for modpack purposes, because many values are hardcoded.
I just added configuration file to change these values, to rebalance this mod.

Resume:
- Energy capacity and energy transfer of armor, tools and weapons are configurable.
- Amounts of upgrades for armor, tools and weapons are configurable.
- Energy storage of each tier of (Multiblock) Energy Core are configurable.
- Now it's possible to change main block of Energy Core structure (It is Block of Redstone by default. But for many modpacks it is very cheap resource for end-game energy storage. These changes allow to redefine it)
- Simplified code of Mob Grinder. Removed additional skull drop for Wither Sleletons (Even without it, Wither Skeletons drop skull pretty often with Mob Grinder. And I removed additional skull drop also because on some modpacks obtaining one from Skeletons is disabled). Added config options to enable looting enchantment for Mob Grinder, change size of energy buffer of this machine and change amount of energy required per kill.
- Now all values of Energy Infuser are configurable.
And finally, updated dependencies of mod.

### CODE REVIEW

**Comment by Dream-Master** [comment]
Some very usefull configs you add there. I like the Idea to replace Redstone Blocks with some more Expensive Materials. :+1:

**Comment by brandon3055** [comment]
Hay there thanks for that! I will look over it later and merge it if it all checks out.

**Comment by OneEyeMaker** [comment]
@brandon3055 
OK. Only one thing I don't changed is manual. Manual is... hardcoded... too...)))
Should I add some info to manual (because now all these values are configurable)?

// And sorry for my English, I'm from Russia.

**Comment by OneEyeMaker** [comment]
I refactored and simplified code, related with upgrades.
Now amount of RF capacity upgrades isn't limited so hard.
Also I separated config options for upgrades of Wyvern and Draconic Flux Capacitors.

... And small API improvements: now it's possible to get maximum amount of upgrades of *specific* stack.

**Comment by Dream-Master** [comment]
@OneEyeMaker 
did you have an email adress i want to ask you some about adding config files. thanks.

**Comment by OneEyeMaker** [comment]
@Dream-Master Yes, I have.
oneeyemaker@gmail.com

**Comment by brandon3055** [comment]
Just pushed my local changes am ready to merge. But looks like there are conflicts you may need to look into.

**Comment by OneEyeMaker** [comment]
@brandon3055 
Please, reformat all your code *__after__* merging and create note for contributors - which code style they should use. Should developers use tab character or spaces (in your code)? It'll prevent merge conflict of this type. And your code will look better ;-)

**Comment by brandon3055** [comment]
Regarding tabs vs spaces. I actually just switched from tabs to spaces so the 1.7.10 code base is a mix of both atm because i havent gotten around to re formatting everything yet.

**Comment by brandon3055** [comment]
If all goes to plan i should be pushing a new version within the hour. I would just like to mention i probably wont be keeping some of these options in 1.9+ because not everything is meant to be configurable.

**Comment by brandon3055** [comment]
@OneEyeMaker Can you please pm me some wear. MC forum, twitter, curse etc. Github dose not have a PM system and i dont know your username anywhere else.

**Comment by OneEyeMaker** [comment]
@brandon3055 
oneeyemaker@gmail.com
Maybe, you like some chat services (Discord?)

**Comment by OneEyeMaker** [comment]
And I'm using the same nickname everywhere. (OneEyeMaker)

**Comment by GreatOrator** [comment]
you can join our discord if you want...

discord.tolkiencraft.com

**Pull request merged**
